### ISSUE TITLE
Consider tag / releases to pair with ICAv2 release cycles.

### ISSUE THREAD

**Issue by alexiswl** [Illumina/ica-sdk-python#1]
Great to see this up and running! 

Would be great to be able to version-control the ica-sdk-python in a given project to match an ICAv2 release cycle

**Comment by kcutler0** [comment]
Yes, will implement with v2.19 update coming this week!

**Comment by kcutler0** [comment]
Added for v2.20 and will do this moving forward

**Comment by alexiswl** [comment]
Thanks @kcutler0, 

I think a tag like `v2.20` would be better than `v2.20-release` but up to you, so long as it is consistent.
